name: Deploy with kubectl (manual setup)
on:
  push:
    branches: [main, feature/workflow]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up kubectl
      uses: azure/setup-kubectl@v3
      with:
        version: "latest"

    - name: Use Kubernetes Config
      uses: azure/k8s-set-context@v3
      with: # Corrected the indentation here
        method: kubeconfig
        kubeconfig: ${{ secrets.KUBECONFIG1 }}

    - name: Debug information
      run: |
        echo "Current working directory: $(pwd)"
        echo "Repository contents:"
        ls -la
        pwd
        date
    - name: Set up Kubernetes cluster
      run: |
        minikube start
        kubectl wait --for=condition=Ready nodes --all --timeout=300s


    - name: Configure kubectl
      run: |
        mkdir -p $HOME/.kube/
        echo "${{ secrets.KUBE_CONFIG1}}" > $HOME/.kube/config
        chmod 600 $HOME/.kube/config

    - name: Test kubectl
      run: |
        kubectl version
        kubectl get nodes
