name: Deploy to Kubernetes t

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up kubeconfig
      run: echo "${{ secrets.KUBECONFIG }}" > $HOME/.kube/config

    - name: Install kubectl
      uses: actions/setup-kubectl@v3

    - name: Verify connection to Kubernetes
      run: kubectl get nodes

   