# jobs:
#   deploy:
#     runs-on: ubuntu-latest
#     steps:
#     - name: Start Minikube
#       run: |
#         sudo apt-get update -q
#         sudo apt-get install -qy conntrack
#         curl -LO https://storage.googleapis.com/minikube/releases/latest/minikube-linux-amd64
#         sudo install minikube-linux-amd64 /usr/local/bin/minikube
#         minikube start --driver=docker

#     - name: Generate kubeconfig
#       run: |
#         mkdir -p ~/.kube
#         cat <<EOF > ~/.kube/config
#         apiVersion: v1
#         clusters:
#         - cluster:
#             certificate-authority: /home/codespace/.minikube/profiles/minikube/apiserver.crt
#             server: https://192.168.49.2:8443
#           name: minikube
#         contexts:
#         - context:
#             cluster: minikube
#             user: minikube-user
#           name: minikube
#         current-context: minikube
#         kind: Config
#         preferences: {}
#         users:
#         - name: minikube-user
#           user:
#             client-certificate: /home/codespace/.minikube/profiles/minikube/client.crt
#             client-key: /home/codespace/.minikube/profiles/minikube/client.key
#         EOF

#     - name: Verify Cluster Connectivity
#       run: |
#         kubectl cluster-info
#         kubectl get nodes

#     # - name: Deploy Application
#     #   run: |
#     #     kubectl apply -f deployment.yaml