name: Deploy to Minikube
on: [pull]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Start Minikube
      run: |
        # Install dependencies
        sudo apt-get update -q
        sudo apt-get install -qy conntrack
        
        # Install Minikube
        curl -LO https://storage.googleapis.com/minikube/releases/latest/minikube-linux-amd64
        sudo install minikube-linux-amd64 /usr/local/bin/minikube
        
        # Start Minikube (required even when using external kubeconfig)
        minikube start --driver=docker --apiserver-ips=127.0.0.1

    - name: Setup Kubeconfig
      run: |
        # Decode the secret
        echo "${{ secrets.MINIKUBE_KUBECONFIG_B64 }}"  > kubeconfig.yaml
        
        # Configure kubectl
        mkdir -p ~/.kube
        cp kubeconfig.yaml ~/.kube/config
        echo "${{ secrets.KUBECONFIG }}"  > ~/.kube/config
        
        # Verify connectivity
        kubectl cluster-info
        kubectl get nodes

    - name: Deploy Application
      run: |
        kubectl apply -f deployment.yaml
